spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/blog
    username: bloguser
    password: 5869
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중: update (운영 시에는 none 권장)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
